#!/usr/bin/env python3
"""Generate an ML-DSA test vector for the on-board verify benchmark.

usage: apps/mldsa_bench/gen_vectors.py <image.bin> <out.h> [44|65|87]
  message = SHA-256 of <image.bin> (32 bytes, what MCUboot signs), context = empty.
  A fresh key pair is generated each run; only the public key and signature are written.
"""
import hashlib
import sys

from cryptography.hazmat.primitives.asymmetric import mldsa

KEYS = {"44": mldsa.MLDSA44PrivateKey, "65": mldsa.MLDSA65PrivateKey,
        "87": mldsa.MLDSA87PrivateKey}


def c_array(name, data):
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    return f"static const uint8_t {name}[{len(data)}] = {{\n\t" + ",\n\t".join(rows) + "\n};\n"


image, out = sys.argv[1], sys.argv[2]
level = sys.argv[3] if len(sys.argv) > 3 else "44"
msg = hashlib.sha256(open(image, "rb").read()).digest()
key = KEYS[level].generate()
sig = key.sign(msg)
pub = key.public_key()
pub.verify(sig, msg)  # host-side check with an independent implementation (OpenSSL via pyca)
pk = pub.public_bytes_raw()

with open(out, "w") as f:
    f.write(f"/* Generated by gen_vectors.py: ML-DSA-{level}, message = SHA-256 of "
            f"{image.split('/')[-1]}, empty context */\n#include <stdint.h>\n\n")
    f.write(c_array("bench_msg", msg))
    f.write(c_array("bench_pk", pk))
    f.write(c_array("bench_sig", sig))
print(f"msg {len(msg)} B, public key {len(pk)} B, signature {len(sig)} B -> {out}")
